### PR TITLE
Table/NoResults Improvements

### LINKED ISSUE #615: When data is empty is it possible to have the table header printed out along with the "No results found." message?
## Griddle version
1.1.0

## Expected Behavior
When data is empty it would be nice if the component printed an empty table with the column headers and a single row displaying an empty message of some sort (eg. No results found.).

## Actual Behavior
A message of "No results found." is returned.

## Steps to reproduce
Provide an empty collection to the griddle component.

### PR DESCRIPTION
**Pull request by dahlbyk**
## Griddle major version

1.x

## Changes proposed in this pull request

Acknowledging that #618 is a lot to handle, I figure I might as well pull some of it out (plus some changes) that should be easier to review in isolation.

* A few of the trivial storybook fixes from #618
* A few dev environment improvements:
  * For LF from Git on Windows
  * [cross-env](https://www.npmjs.com/package/cross-env) for builds on Windows
  * [EditorConfig](http://editorconfig.org/) for anyone
* `Table`, `TableHeading` and `NoResults` are now generally more resilient
* `NoResults` props actually work
* If `data` is `null` or `undefined`, `NoResults` is rendered instead of runtime errors (with tests!)
* `NoResults` now receives `columnIds` and `columnTitles` (consistent with `TableHeading`; mostly useful for column count)

## Why these changes are made

The primary use case, for which I added a story, is a `Table` component which renders `NoResults` below its `TableHeading` instead of having `NoResults` replace the whole `<table />`.

Closes #615 

## Are there tests?

Yes!

### CODE REVIEW

**Comment by dahlbyk** [comment]
> Revert "Expose column data to NoResults"

After further consideration, it seems more appropriate for column data not to be included by default, since it's relatively simple to override `NoResultsContainer`. As such, I've reverted that change and updated the story to preserve the desired behavior without modifying the default component.

File: stories/index.js [hunk 1]
```diff
@@ -666,6 +664,69 @@ storiesOf('TableHeading', module)
...
+
+  .add('empty with columns', () => {
+    const components = {
+      Table: ({ TableHeading, TableBody, NoResults, style, visibleRows }) => (
+        <table style={style}>
+          <TableHeading />
+          { visibleRows ? (TableBody && <TableBody />) : (NoResults && <NoResults />) }
+        </table>
+      ),
+      NoResultsContainer: compose(
```
Comment (dahlbyk) [inline stories/index.js]: This seems to work as expected... Is there a reason your `Container` components use the following pattern?

```javascript
const WhateverContainer = OriginalComponent => compose(
  ...
)(props => <OriginalComponent {...props} />);
```

Comment (ryanlanciaux) [inline stories/index.js]: The main reason for making our container components higher-order components rather than wrappers is that we are assuming that they may be composed via plugins, etc. 

There may be a better / clearer way to do this moving forward but that was the initial intent (if I understand correctly :+1:)

Comment (dahlbyk) [inline stories/index.js]: I may be wrong, but my understanding of `compose()` is that it's already returning a higher-order component. The outer arrow function seems to be redundant; `compose` is already returning a function that takes in the original component and returns the composed component.

Comment (ryanlanciaux) [inline stories/index.js]: You're totally right - I'm going to think a little bit about why we're doing this (totally possible it's oversight). Thanks!

**Comment by ryanlanciaux** [comment]
This is excellent thank you and sorry about the delay! :+1:

I'm going to follow-up some more on the arbitrarily nested HoC -- That shouldn't block here.
