### PR TITLE
Fixed Many-ColumnDefinition Ordering

### LINKED ISSUE #619: columns get somehow shuffled when there are more than 8 columns in ColumnDefinition
## Griddle version

1.1.0 / 1.2.0
chrome & safari (others not tested)

## Expected Behavior

Columns should always be in the same order as defined in `<RowDefinition><ColumnDefinition .. /></RowDefinition>`

## Actual Behavior

if there are more than 8 columns, the order is different. It's always the same, but i did not found the logic how it gets shuffled.

## Steps to reproduce

add more than 8 columnDefinition

## Pull request with failing test or storybook story with issue

I hope i can do this later, but maybe someone has an idea why this is happening. its really odd ;-o

### PR DESCRIPTION
**Pull request by dahlbyk**
## Griddle major version

1.x

## Changes proposed in this pull request

It's still not clear to me what precisely is causing the order to change, but it seems wise in general to set column `order` earlier to use everywhere (which fixes the bug).

Also cleaned up `columnUtils` a bit. 

## Why these changes are made

Fixes #619.

## Are there tests?

Story!

### CODE REVIEW

File: src/utils/columnUtils.js [hunk 1]
```diff
@@ -1,23 +1,14 @@
...
-
-function containsColumnPropertiesObject(rowProperties) {
-  return rowProperties && rowProperties.props && rowProperties.props.children;
-}
-
 /** Gets a column properties object from an array of columnNames
  * @param {Array<string>} columns - array of column names
  */
-export function getColumnPropertiesFromColumnArray(columns) {
+function getColumnPropertiesFromColumnArray(columnProperties, columns) {
```
Comment (dahlbyk) [inline src/utils/columnUtils.js]: Technically this is a breaking change, but there's really no reason for this to have been used publicly.

Comment (ryanlanciaux) [inline src/utils/columnUtils.js]: Agree that this is more an internal method

**Comment by ryanlanciaux** [comment]
:+1:

**Comment by andreme** [comment]
Thanks @dahlbyk
