### PR TITLE
onSort with *correct* sortProperties

### LINKED ISSUE #716: onSort event not giving sortAscending ascending property
## Expected Behavior
We can also pass custom events in order to controlling paging, sorting etc...
I am facing issue with onSort event, It will return sortProperty with **id** and **sortAscending** property. like
If i am clicking on **name** column then onSort should return:
`{ id: 'name', sortAscending: true }`
and if i again click on **name** column then onSort should return:
`{ id: 'name', sortAscending: false }`

## Actual Behavior
but actually it is returning only **id** property in the both case not the **sortAscending**
`{ id: 'name' }`

## Steps to reproduce
1. Griddle with static data
2. Pass events to griddle

```
 let pagingEvents = {
     onFilter: (filterText) = > {
         console.log("filterText", filterText)
     },
     onSort: (sortProperties) = > {
         console.log("sortProperties", sortProperties)
     },
     onNext: () = > {
         console.log("on Next callback")
     },
     onPrevious: () = > {
         console.log("on Prev callback")
     },
     onGetPage: (pageNumber) = > {
         console.log("pageNumber", pageNumber)
     },
 }

<Griddle data={results} plugins={[plugins.LocalPlugin]} styleConfig={styleConfig} events={pagingEvents}>
    <RowDefinition>
        <ColumnDefinition id="name" title="Name" width={200} style={{ textAlign: 'center' }} />
        <ColumnDefinition id="gender" title="Gender" width={80} style={{ textAlign: 'center' }} />
        <ColumnDefinition id="height" title="Height" width={50} style={{ textAlign: 'center' }} />
    </RowDefinition>
</Griddle>

```

### PR DESCRIPTION
**Pull request by dahlbyk**
## Griddle major version

1.x

## Changes proposed in this pull request

`onSort` is now fired just before the new `sortProperties` are dispatched.

This essentially renders `TableHeadingCell` obsolete, but deleting it is a potentially breaking change.

### Idea
What if events were fired from a Redux middleware instead of click handlers?

## Why these changes are made

Close #716; #717 was insufficient.

## Are there tests?

Existing story now demonstrates expected behavior.

It seems like a new React version changed behavior when `render()` returns a string, so the TS story has been adjusted.

### CODE REVIEW

File: src/components/TableHeadingCellEnhancer.js [hunk 1]
```diff
@@ -1,21 +1,4 @@
...
-  mapProps(({ events: { onSort }, ...props }) => ({
-    ...props,
-    onClick: combineHandlers([
-      () => onSort && onSort(props.sortProperty || { id: props.columnId }),
-      props.onClick,
-    ]),
-  }))
-)(props => <OriginalComponent {...props} />);
+// Obsolete
+const EnhancedHeadingCell = OriginalComponent => OriginalComponent;
```
Comment (joellanciaux) [inline src/components/TableHeadingCellEnhancer.js]: Can this be removed?

Comment (dahlbyk) [reply src/components/TableHeadingCellEnhancer.js]: It can, but it's _technically_ a breaking change. Glad to remove if you're not concerned.

Comment (ryanlanciaux) [reply src/components/TableHeadingCellEnhancer.js]: Just to double confirm - we're leaving this here to avoid causing a potential breaking change right? I think we're maybe just outside the realm of where a 2.0 release makes sense. If I'm understanding correctly, we can leave this here for now to avoid breaking change and remove the obsolete field in a 2.0 version.

Thoughts?

Comment (dahlbyk) [reply src/components/TableHeadingCellEnhancer.js]: Correct. I left it as a no-op to be cleaned up for a 2.0 release.

The chances someone is actually depending on this seem quite low, but it's been exported as part of the public API.

**Comment by dahlbyk** [comment]
On re-review I noticed a few gaps between core and local versions of `TableHeadingCellContainer`, so I've added a commit to close the gap (mostly from #699).
